### ISSUE TITLE
Limitations ?

### ISSUE THREAD

**Issue by gedw99** [influx6/gu#1]
Not to be an arse, but what are the current limitations ?
The design looks pretty usable - congrats.

**Comment by influx6** [comment]
None taking. The only limitations that must be firmly declared is 

1. That this library is not a react like library where structures are able to bind and listen for change, the complexity of that approach is undesired.
2 The library takes a proactive play where the developer uses either a function call or the notification system to update changes to screen and not a auto-update approach.
3. It has no synchronization primitive for both server and client but rather takes a simple approach of where the client takes control of the page rendering by re-rendering at target spots, hence developers should not expect a magical hydration-dehydration mechanism.
