### ISSUE TITLE
Examples do not work.

### ISSUE THREAD

**Issue by Aukstkalnis** [influx6/gu#5]
Platform: Windows 7 x64
Golang: 1.7.4

Hello example prints:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5f45a9]

goroutine 1 [running]:
panic(0x748d80, 0xc0420040b0)
        c:/go/src/runtime/panic.go:500 +0x1af
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0x7c9d11, 0x8, 0xc0420260e8)
        D:/gopath/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x29
honnef.co/go/js/dom.(*window).Document(0xc0420260e8, 0xc0420260e8, 0xc0420cdf08)

        D:/gopath/src/honnef.co/go/js/dom/dom.go:969 +0x4a
main.main()
        D:/gopath/src/github.com/influx6/gu/examples/hello/hello.go:13 +0x69

D:\gopath\src\github.com\influx6\gu\examples\hello>

And susribe example do not build at all. "go build" command do not create executable file.

**Comment by influx6** [comment]
Thanks for getting in touch, the library is aimed at providing html rendering, to run examples, simply open the index.html file within the corresponding example directory.

**Comment by influx6** [comment]
To simplify you started I have included a readme in the examples folder with directions. 

Do please get back incase you are facing any other difficulties.

**Comment by influx6** [comment]
Sorry please close the issue once you feel satisfied.

**Comment by Aukstkalnis** [comment]
Thanks for quick tips :) I think I understand how I should use examples :)
